import { describe, expect, it } from 'vitest'

import { parseClusterHubJoinUri } from './clusterHubUri'

describe('parseClusterHubJoinUri', () => {
  it('parses canonical Hub join URIs with the domain id in query params', () => {
    expect(parseClusterHubJoinUri('buihub://hub.example.com/domain?id=customer-1.test&domain_token=abc123&hub_protocol=https')).toEqual({
      domainId: 'customer-1.test',
      host: 'hub.example.com',
      protocol: 'https',
      token: 'abc123',
    })
  })

  it('parses Cloudflare Hub URIs generated by the Hub admin page', () => {
    expect(parseClusterHubJoinUri('buihub://hub-cluster.test/domain?id=customer-1.test&domain_token=domain-secret&hub_protocol=https')).toEqual({
      domainId: 'customer-1.test',
      host: 'hub-cluster.test',
      protocol: 'https',
      token: 'domain-secret',
    })
  })

  it('keeps ports and accepts the legacy token parameter during rollout', () => {
    expect(parseClusterHubJoinUri('buihub://localhost:8787/domain?id=dev.example.com&token=legacy')).toEqual({
      domainId: 'dev.example.com',
      host: 'localhost:8787',
      protocol: 'http',
      token: 'legacy',
    })
  })

  it('accepts direct domain paths for compact copied URIs', () => {
    expect(parseClusterHubJoinUri('buihub://hub.example.com/customer-1.test?domain_token=compact')).toEqual({
      domainId: 'customer-1.test',
      host: 'hub.example.com',
      protocol: 'https',
      token: 'compact',
    })
  })

  it('accepts query-only Hub join URIs with id and domain_token parameters', () => {
    expect(parseClusterHubJoinUri('buihub://hub-cluster.test?id=customer-1.test&domain_token=domain-secret')).toEqual({
      domainId: 'customer-1.test',
      host: 'hub-cluster.test',
      protocol: 'https',
      token: 'domain-secret',
    })
  })

  it('accepts camelCase domain token parameters copied from alternate Hub clients', () => {
    expect(parseClusterHubJoinUri('buihub://hub.example.com/domain?id=customer-1.test&domainToken=camel-token')).toEqual({
      domainId: 'customer-1.test',
      host: 'hub.example.com',
      protocol: 'https',
      token: 'camel-token',
    })
  })

  it('rejects URIs that embed another URL scheme after buihub', () => {
    expect(parseClusterHubJoinUri('buihub://https://hub.example.com/domain/customer-1.test?domain_token=abc123')).toBeNull()
  })

  it('rejects canonical domain URIs that omit the id parameter', () => {
    expect(parseClusterHubJoinUri('buihub://hub.example.com/domain?domain_token=abc123')).toBeNull()
  })
})
